PUSH=ru.nsu.fit.dkuzin.lab2.commands.PushCommand
POP=ru.nsu.fit.dkuzin.lab2.commands.PopCommand
PRINT=ru.nsu.fit.dkuzin.lab2.commands.PrintCommand
DEFINE=ru.nsu.fit.dkuzin.lab2.commands.DefineCommand
+=ru.nsu.fit.dkuzin.lab2.commands.AddCommand
-=ru.nsu.fit.dkuzin.lab2.commands.SubCommand
*=ru.nsu.fit.dkuzin.lab2.commands.MulCommand
/=ru.nsu.fit.dkuzin.lab2.commands.DivCommand
SQRT=ru.nsu.fit.dkuzin.lab2.commands.SqrtCommand